name: MacBuild

on:
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_macos:
    name: macOS
    runs-on: macos-10.14

    env:
        DEVELOPER_DIR: /Applications/Xcode_11.3.app/Contents/Developer

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Build
        run: ./scripts/build_iosx.sh

      - name: Package
        run: ./scripts/package.sh

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2.2.4
        with:
          path: webrtc_*.zip
